server:
  port: 8443  #서버 포트 번호 8443 (https의 기본 포트는 443)
  
  servlet:
    session:
      tracking-modes: cookie  #URL에 jsessionid가 보여질 때
 
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: 1234qwer
            
spring:
  application:
    name: study-project
    
  #Spring devTools 관련 설정
  devtools:
    livereload:
      enabled: true
      
    restart:
      enabled: true
      
  thymeleaf:
    cache: false
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
  
    hikari: 
      username: studyproject
      password: study1234
      minimum-idle: 1
      maximum-pool-size: 2
      connection-timeout: 30000
  jpa:
    #sql 보기
    show-sql: true
    
    hibernate:
      ddl-auto: validate
      
    properties:
      dialect: org.hibernate.dialect.OracleDialect
      
      #sql 예쁘게 보기  
      hibernate:
        format_sql: true   
    
    
logging:
  level:
    root: info
    
    #?에 어떤 값이 들어갔는지 확인하기    
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    
 